name: 'Conventional PRs'
description: 'Validates PR titles and commit messages against Conventional Commits specification'
author: 'scarf005'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  config:
    description: 'Path to configuration file'
    required: false
  github_token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  validate_pr_title:
    description: 'Validate PR title'
    required: false
    default: 'true'
  validate_commits:
    description: 'Validate commit messages'
    required: false
    default: 'false'
  validate_both:
    description: 'Validate both PR title and commits'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_CONFIG: ${{ inputs.config }}
    INPUT_VALIDATE_PR_TITLE: ${{ inputs.validate_pr_title }}
    INPUT_VALIDATE_COMMITS: ${{ inputs.validate_commits }}
    INPUT_VALIDATE_BOTH: ${{ inputs.validate_both }}
