import { cp, mkdir, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { build } from "esbuild"

const rootDir = resolve(fileURLToPath(new URL("..", import.meta.url)))
const actionDir = resolve(rootDir, "action")
const entryPoint = resolve(actionDir, "src/index.js")
const outDir = resolve(actionDir, "dist")
const wasmSource = resolve(rootDir, "lib/rs_lib.wasm")

const generatedBanner =
  "// @generated by scripts/build-action.mjs -- do not edit"

const equalBytes = (left, right) => {
  if (left.length !== right.length) {
    return false
  }

  for (let index = 0; index < left.length; index += 1) {
    if (left[index] !== right[index]) {
      return false
    }
  }

  return true
}

const buildAction = async (directory) => {
  await rm(directory, { recursive: true, force: true })
  await mkdir(directory, { recursive: true })

  await build({
    entryPoints: [entryPoint],
    outfile: resolve(directory, "index.js"),
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    banner: { js: generatedBanner },
    logLevel: "info",
  })

  await cp(wasmSource, resolve(directory, "rs_lib.wasm"))
}

const checkAction = async () => {
  const tempDir = await Deno.makeTempDir({
    dir: tmpdir(),
    prefix: "conventional-prs-action-",
  })

  try {
    const tempOutDir = resolve(tempDir, "dist")
    await buildAction(tempOutDir)

    for (const file of ["index.js", "rs_lib.wasm"]) {
      const expected = await readFile(resolve(tempOutDir, file))
      const actual = await readFile(resolve(outDir, file))

      if (!equalBytes(expected, actual)) {
        throw new Error(
          `action bundle is out of date: action/dist/${file}. Run \`deno task build:action\``,
        )
      }
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true })
  }
}

if (Deno.args.includes("--check")) {
  await checkAction()
} else {
  await buildAction(outDir)
}
